https://github.com/xbeat/Machine-Learning/blob/main/Exploring%20Self-Attention%20in%20Transformers%20with%20Python.md#

Self-attention is a key mechanism in transformer models that allows the model to weigh the importance of different parts of the input when processing each element. 

In [1]:
import numpy as np

def self_attention(query, key, value):
    # Compute attention scores
    scores = np.dot(query, key.T) / np.sqrt(key.shape[1])
    print("scores",scores)
    
    # Apply softmax to get attention weights
    weights = np.exp(scores) / np.sum(np.exp(scores), axis=1, keepdims=True)
    print("weights:",weights)
    
    # Compute weighted sum of values
    output = np.dot(weights, value)
    print("output", output)
    
    return output

In [2]:
# Example usage
query = np.array([[1, 0, 1], [0, 1, 1]])
key = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]])
value = np.array([[1, 0], [0, 1], [1, 1]])

result = self_attention(query, key, value)
print("Self-attention output:")
print(result)

scores [[0.57735027 1.15470054 0.57735027]
 [0.57735027 0.57735027 1.15470054]]
weights: [[0.26445846 0.47108308 0.26445846]
 [0.26445846 0.26445846 0.47108308]]
output [[0.52891692 0.73554154]
 [0.73554154 0.73554154]]
Self-attention output:
[[0.52891692 0.73554154]
 [0.73554154 0.73554154]]
